apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keystone
  namespace: keystone
  labels:
    app.kubernetes.io/name: keystone
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - keystone.example.com
      secretName: keystone-tls
  rules:
    - host: keystone.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keystone
                port:
                  number: 80
