apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: keystone
  namespace: keystone
  labels:
    app.kubernetes.io/name: keystone
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: keystone
